### ISSUE TITLE
Mesa + panfrost driver fails to build

### ISSUE THREAD

**Issue by imapotatoalso** [gentoo/musl#334]
Salute!
It appears when panfrost use flag is enabled, mesa doesn't build.
https://bin.snopyta.org/?b27d032f0a884d4e#GXpQcnUSyKgopxpTKmAbtFVQNRvicWoV9GNhu6vY5g45
I'm not sure if I'm doing something wrong, or if Panfrost isn't available.
The error is similar with gcc.
Thanks in advance!

**Comment by stefson** [comment]
I'm also having an rpi2 running with musl, but haven't tested panfrost yet. If you seek support, please upload the compressed build log here, plus the output of emerge --info

unless you don't provide these, there are not enough data points to work with. if you've got more than one version of gcc/binutils, please tell me which is your eselected one. thanks.

**Comment by imapotatoalso** [comment]
Ok, I'll do that after I get home.
Thank you!

**Comment by imapotatoalso** [comment]
These are my build logs and my emerge --info output

[info.txt](https://github.com/gentoo/musl/files/5119981/info.txt)
[build.log](https://github.com/gentoo/musl/files/5119982/build.log)

**Comment by stefson** [comment]
@imapotatoalso the fix for the compile failure was easy, since I learned that this was fixed in mesa-9999. After trying all newer versions then 20.0.8, it showed that they all have this fixed, thus a simple bump to the yet unstable 20.1.x branch will suffice. 

Can you please test the pullrequest and do a runtime test? I can only work from chroot at the moment. Also if you happen to know how to enable panfrost at runtime, please share that information with me. thanks.

**Comment by imapotatoalso** [comment]
sure!

**Comment by imapotatoalso** [comment]
I'm going to have to do some debugging, xorg gave "Illegal instruction at axad3fa782" instead of starting

**Comment by stefson** [comment]
you should try the following:

update to the latest kernel to get the latest bug fixes in panfrost
update to the latest musl-1.2.1, it has had many bug fixes for arm
update to mesa-9999, I can push the ebuild in the evening if you need help with that

if none of these help, contact upstream and ask for help. please link back your issue to this, so that I'm able to follow it.

**Comment by imapotatoalso** [comment]
I will.
Quick question, is it the latest kernel or the latest stable kernel I should install?

**Comment by stefson** [comment]
I don't even know what sources you're using, so I can only answer the question as: latest non mainline kernel you can get to boot, maybe 5.8.x would be good? 

And also, maybe use gcc to compile mesa. Don't pick to many foes, musl is fragile with arm.

**Comment by imapotatoalso** [comment]
Oh I was using 5.4.38 I think. I already tried to compile with gcc, it gave the same error though. I'm using musl v1.1.24. I'll look into mesa-9999.

**Comment by stefson** [comment]
there has been some activity in the area of the panfrost kernel module code in the kernel recently, and it should be easy to use the newest kernel just for testing. The mesa master git branch is under heavy developement at the moment, so my bet for a fix is here, but usually you need latest kernel to get it fixed. 

again, musl-1.2.1 has many bug fixes for arm. 

if none helps, please talk to upstream

**Comment by imapotatoalso** [comment]
Thank you!
I'll close this issue then.

**Comment by stefson** [comment]
were you able to solve the problem?

**Comment by imapotatoalso** [comment]
Ok, I resolved the issue by simply updating mesa to 9999 today.

**Comment by stefson** [comment]
great, so can you please post how to reproduce your success, so that I can try to understand better and post a possible backport? Also I'm keen on trying panfrost for myself when there's enough free cpu cycles, so I need kernel version and if yours is a rpi2 the config.gz, please.

**Comment by imapotatoalso** [comment]
Cool, I'm using kernel version 5.4.48. I'm using a chromebook c201 not a raspi but if you want I can still post the config.gz.

**Comment by imapotatoalso** [comment]
I'll close this issue then.
