### ISSUE TITLE
new 17.0 profiles

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#79]
hey there, 

I wonder what is going on with the 17.0 profiles and musl? 

Is there an upgrade path to enable pie? 

thanks

**Comment by karlguy** [comment]
The new 17.0 profiles only affect gentoo on glibc. Musl uses totally different profiles, and pie has already been enabled by default on both vanilla and hardened.

**Comment by blueness** [comment]
musl profiles do not inherit from 17.0 profiles.  i debated whether to do that or not, but i decided not to because it will add unnecessary complexity.  sooner or later people will start to add glibc specific stuff which we'll have to undo in the musl profiles.  its better to keep the profiles shallow.
