### ISSUE TITLE
Musl profile - VIDEO_CARDS option problem

### ISSUE THREAD

**Issue by LeonSkoog** [gentoo/musl#80]
Hi,
I have problem with `VIDEO_CARDS` option with hardened/linux/musl/amd64 profile.
[>eselect profile list](https://pastebin.com/aCetrYR8)

When I **don't** set `VIDEO_CARDS` option in make.conf then `emerge --info` return `VIDEO_CARDS="dummy fbdev v4l"`

[>cat /etc/portage/make.conf](https://pastebin.com/cwiRuuZG)
[>emerge --info](https://pastebin.com/yDwQEVxZ)

But when I set `VIDEO_CARDS="i965 intel"` option in make.conf then `VIDEO_CARDS` option disappeared from `emerge --info`.

[>cat /etc/portage/make.conf](https://pastebin.com/bcvee3qg)
[>emerge --info](https://pastebin.com/Db0EQvAR)

My temporary solution is to edit `/usr/portage/profiles/arch/base/use.mask `
and change lines 141,142:
```
video_cards_i965
video_cards_intel
```
into:
```
-video_cards_i965
-video_cards_intel
```

After these changes, `VIDEO_CARDS="i965 intel"` is reported by `emerge --info`.

I think that `VIDEO_CARDS` is somehow masked by musl profile, do you have idea how to fix it?
Or can you provide permanent workaround?

**Comment by stefson** [comment]
There are some problems with the video_cards useflags and musl profiles. The arm profile for instance hardmasks the vc4 useflag, and some other arm exclusive drivers. I once opened a bug about this (631568) , and the problem seems to be that for my case all arm specific stuff is masked for all arches, but later on unmasked on the arm profile. However, current musl profiles don't include /usr/portage/profiles/arch/arm* , which is where the unmasking takes place. 

I think that /etc/portage/profile/package.use.unmask is the right place to unmask them on your own. I guess the syntax works like this

`
xorg-drivers -video_cards_i965 -video_cards_intel `

**Comment by LeonSkoog** [comment]
It works!
I made changes in  /etc/portage/profile/use.mask 
```
-video_cards_i965 
-video_cards_intel
```

Thanks for hint!
